version: '3'

services:
  morello-sdk-qemu:
    image: digicatapult/morello-sdk:v1.0.1
    container_name: qemu
    command: /bin/bash -c "
        qemu-system-morello
        -machine virt,gic-version=3
        -cpu morello
        -bios edk2-aarch64-code.fd
        -m 2048
        -nographic
        -drive if=none,file=/home/cheri/cheribsd-minimal-morello-purecap.img,id=drv,format=raw
        -device virtio-blk-pci,drive=drv
        -device virtio-net-pci,netdev=net0
        -netdev 'user,id=net0,hostfwd=tcp::19507-:22'
        -device virtio-rng-pci
        -snapshot"
    ports:
      - "1022:19507"
    expose:
      - "19507"
  morello-api:
    image: digicatapult/morello-api:v0.6.4
    container_name: api
    ports:
      - "3001:3000"
    environment:
      - MORELLO_HOST=qemu
      - MORELLO_PORT=19507
